;; OBJ TILE
;; Size
OBJ_TILE              = $08
OBJ_TILE_SET          = $24 ;;
;; Map
OBJ_TILE_TOP_LEFT     = $00
OBJ_TILE_TOP_RIGHT    = $01
OBJ_TILE_BOTTOM_LEFT  = $02
OBJ_TILE_BOTTOM_RIGHT = $03
OBJ_TILE_COLOR        = $04
OBJ_TILE_COLLISION    = $05
OBJ_TILE_TYPE         = $06
OBJ_TILE_OTHER        = $07
;; Types
OBJ_TILE_TYPE_NONE      = $00
OBJ_TILE_TYPE_EXIT_DOWN = $01
OBJ_TILE_TYPE_EXIT_UP   = $02
OBJ_TILE_TYPE_CACHE     = $03

;; OBJ CREATURE
;; Size
OBJ_CREATURE        = $08
OBJ_CREATURE_MAX    = $04
;; Map
OBJ_CREATURE_STATUS = $00
OBJ_CREATURE_HEALTH = $01
OBJ_CREATURE_XPOS   = $02
OBJ_CREATURE_YPOS   = $03
OBJ_CREATURE_MOVE   = $04
OBJ_CREATURE_KNOCK  = $05
OBJ_CREATURE_SPRITE = $06
OBJ_CREATURE_HIT    = $07

;; OBJ COLLECTABLE
;; Size
OBJ_COLLECTABLE         = $04
OBJ_COLLECTABLE_MAX     = $04
;; Map
OBJ_COLLECTABLE_STATUS  = $00
OBJ_COLLECTABLE_TYPE    = $01
OBJ_COLLECTABLE_XPOS    = $02
OBJ_COLLECTABLE_YPOS    = $03
;; Types
OBJ_COLLECTABLE_TYPE_ROCK    = $00
OBJ_COLLECTABLE_TYPE_COIN    = $01
OBJ_COLLECTABLE_TYPE_BOMB    = $02
OBJ_COLLECTABLE_TYPE_KNIFE   = $03
OBJ_COLLECTABLE_TYPE_RED_HRB = $04
OBJ_COLLECTABLE_TYPE_BLU_HRB = $05
OBJ_COLLECTABLE_TYPE_GRN_HRB = $06
OBJ_COLLECTABLE_TYPE_YLW_HRB = $07
