;; OBJ CREATURE
;; Size
OBJ_CREATURE        = $08
OBJ_CREATURE_MAX    = $04
;; Map
OBJ_CREATURE_STATUS = $00
OBJ_CREATURE_HEALTH = $01
OBJ_CREATURE_XPOS   = $02
OBJ_CREATURE_YPOS   = $03
OBJ_CREATURE_MOVE   = $04
OBJ_CREATURE_KNOCK  = $05
OBJ_CREATURE_SPRITE = $06
OBJ_CREATURE_HIT    = $07
;; Map
IDX_CREATURE_PLAYER      = $00 ;; 4 Tiles
IDX_CREATURE_PLAYER_FIRE = $04

IDX_CREATURE_BULLET_A    = $05
IDX_CREATURE_BULLET_B    = $06
IDX_CREATURE_BULLET_C    = $07
IDX_CREATURE_BULLET_D    = $08
IDX_CREATURE_BULLET_E    = $09
IDX_CREATURE_BULLET_F    = $0A

IDX_CREATURE_ENEMY_A = $02
IDX_CREATURE_ENEMY_B = $02
IDX_CREATURE_ENEMY_C = $03
IDX_CREATURE_ENEMY_D = $04
IDX_CREATURE_ENEMY_E = $05

;; OBJ BULLET
;; Size
OBJ_BULLET        = $04
;; Map
OBJ_BULLET_STATUS = $00
OBJ_BULLET_SPRITE = $01
OBJ_BULLET_XPOS   = $02
OBJ_BULLET_YPOS   = $03

;; OBJ COLLECTABLE
;; Size
OBJ_COLLECTABLE         = $04
OBJ_COLLECTABLE_MAX     = $04
;; Map
OBJ_COLLECTABLE_STATUS  = $00
OBJ_COLLECTABLE_TYPE    = $01
OBJ_COLLECTABLE_XPOS    = $02
OBJ_COLLECTABLE_YPOS    = $03
;; Types
OBJ_COLLECTABLE_TYPE_PARTA   = $01
OBJ_COLLECTABLE_TYPE_PARTB   = $02
OBJ_COLLECTABLE_TYPE_PARTC   = $03
