CONTROLLER_DIRECTION_DOWN = %00000100

.macro ControllerAGateDirectionDown ExitBranch
  LDA controller_a
  AND #CONTROLLER_DIRECTION_DOWN
  CMP #CONTROLLER_DIRECTION_DOWN
  BNE ExitBranch

  LDA controller_ap
  AND #CONTROLLER_DIRECTION_DOWN
  CMP #CONTROLLER_DIRECTION_DOWN
  BNE ExitBranch
.endmacro
